// <auto-generated />
using System;
using Infra.Configuracao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20230910181926_adustPedidoServicoNM")]
    partial class adustPedidoServicoNM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Entidades.Animal", b =>
                {
                    b.Property<int>("ID_Animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Animal"));

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Animal");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Entities.Entidades.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_CPF");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_ROLE");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Entidades.Cliente", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Cliente"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Cliente");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Entities.Entidades.Compra", b =>
                {
                    b.Property<long>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCompra"));

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<long>("IdFornecedor")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("IdCompra");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdFornecedor");

                    b.ToTable("COMPRAS");
                });

            modelBuilder.Entity("Entities.Entidades.Consulta", b =>
                {
                    b.Property<int>("ID_Consulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Consulta"));

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FimConsulta")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Animal")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("ID_Veterinario")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioConsulta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID_Consulta");

                    b.HasIndex("ID_Animal");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("ID_Veterinario");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("Entities.Entidades.Consulta_Exame", b =>
                {
                    b.Property<int>("ID_Consulta")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ID_Exame")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataExame")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Consulta", "ID_Exame");

                    b.HasIndex("ID_Exame");

                    b.ToTable("Consulta_Exame");
                });

            modelBuilder.Entity("Entities.Entidades.Estoque", b =>
                {
                    b.Property<long>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEstoque"));

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Prateleira")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstoque");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("ESTOQUES");
                });

            modelBuilder.Entity("Entities.Entidades.Exame", b =>
                {
                    b.Property<int>("ID_Exame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Exame"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Custo")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Exame");

                    b.HasIndex("ClienteId");

                    b.ToTable("Exame");
                });

            modelBuilder.Entity("Entities.Entidades.Familia", b =>
                {
                    b.Property<long>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFamilia"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdFamilia");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("Entities.Entidades.Fornecedor", b =>
                {
                    b.Property<long>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFornecedor"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdFornecedor");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("FORNECEDORES");
                });

            modelBuilder.Entity("Entities.Entidades.ItemProdutoCompra", b =>
                {
                    b.Property<long>("IdCompra")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompraIdCompra")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("date");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("Imposto")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Lote")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PrecoTotal")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("QuantidadeTotal")
                        .HasColumnType("int");

                    b.Property<string>("StatusEntrega")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCompra", "IdProduto");

                    b.HasIndex("CompraIdCompra");

                    b.HasIndex("IdProduto");

                    b.ToTable("ITENS_PRODUTOS_COMPRA");
                });

            modelBuilder.Entity("Entities.Entidades.ItemProdutoEstoque", b =>
                {
                    b.Property<long?>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("IdEstoque")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("date");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProduto", "IdEstoque");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdEstoque");

                    b.ToTable("ITENS_PRODUTO_ESTOQUES");
                });

            modelBuilder.Entity("Entities.Entidades.ItemProdutoVenda", b =>
                {
                    b.Property<long>("IdVenda")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Quantidade")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TotalProdutosVendas")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdVenda", "IdProduto");

                    b.HasIndex("IdProduto");

                    b.ToTable("ITENS_PRODUTOS_VENDAS");
                });

            modelBuilder.Entity("Entities.Entidades.Mercadoria", b =>
                {
                    b.Property<long>("IdMercadoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMercadoria"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdMercadoria");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Mercadorias");
                });

            modelBuilder.Entity("Entities.Entidades.NotaFiscal", b =>
                {
                    b.Property<long>("IdNotaFiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNotaFiscal"));

                    b.Property<string>("ClienteCnpjCpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClienteEndereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<long?>("IdVendaServicoPagamento")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("IdNotaFiscal");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdVendaServicoPagamento");

                    b.ToTable("NOTA_FISCAL");
                });

            modelBuilder.Entity("Entities.Entidades.PedidoServicos", b =>
                {
                    b.Property<long>("IdPedidoServicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPedidoServicos"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalPedido")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("IdPedidoServicos");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("PEDIDO_SERVICOS");
                });

            modelBuilder.Entity("Entities.Entidades.PedidoServicosRelacao", b =>
                {
                    b.Property<long>("IdPedidoServicos")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("IdServico")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("IdPedidoServicos", "IdServico");

                    b.HasIndex("IdServico");

                    b.ToTable("PEDIDO_SERVICOS_RELACAO");
                });

            modelBuilder.Entity("Entities.Entidades.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProduto"));

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<long>("IdUnspsc")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PrecoCompra")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProduto");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdUnspsc");

                    b.ToTable("PRODUTOS");
                });

            modelBuilder.Entity("Entities.Entidades.Secretaria", b =>
                {
                    b.Property<int>("ID_Secretaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Secretaria"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Secretaria");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Secretarias");
                });

            modelBuilder.Entity("Entities.Entidades.Segmento", b =>
                {
                    b.Property<long>("IdSegmento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSegmento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdSegmento");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Segmentos");
                });

            modelBuilder.Entity("Entities.Entidades.Servico", b =>
                {
                    b.Property<long>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdServico"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<long>("IdUnspsc")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("IdServico");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdUnspsc");

                    b.ToTable("SERVICOS");
                });

            modelBuilder.Entity("Entities.Entidades.UnspscCode", b =>
                {
                    b.Property<long>("IdUnspsc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUnspsc"));

                    b.Property<string>("CodigoSfcm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<long>("IdClasse")
                        .HasColumnType("bigint");

                    b.Property<long>("IdFamilia")
                        .HasColumnType("bigint");

                    b.Property<long>("IdMercadoria")
                        .HasColumnType("bigint");

                    b.Property<long>("IdSegmento")
                        .HasColumnType("bigint");

                    b.HasKey("IdUnspsc");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdFamilia");

                    b.HasIndex("IdMercadoria");

                    b.HasIndex("IdSegmento");

                    b.ToTable("UnspscCodes");
                });

            modelBuilder.Entity("Entities.Entidades.UsuarioSistemaClinica", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Usuario");

                    b.ToTable("UsuarioSistemaClinica");
                });

            modelBuilder.Entity("Entities.Entidades.Venda", b =>
                {
                    b.Property<long>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVenda"));

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("date");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdVenda");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("VENDA");
                });

            modelBuilder.Entity("Entities.Entidades.VendaServicoPagamento", b =>
                {
                    b.Property<long>("IdVendaServicoPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVendaServicoPagamento"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<long?>("IdPedidoServicos")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdVenda")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("IdVendaServicoPagamento");

                    b.HasIndex("ID_Usuario");

                    b.HasIndex("IdPedidoServicos");

                    b.HasIndex("IdVenda");

                    b.ToTable("VENDA_SERVICO_PAGAMENTO");
                });

            modelBuilder.Entity("Entities.Entidades.Veterinario", b =>
                {
                    b.Property<int>("ID_Veterinario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Veterinario"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especializacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Veterinario");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Veterinario");
                });

            modelBuilder.Entity("Infra.Configuracao.Classe", b =>
                {
                    b.Property<long>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdClasse"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("IdClasse");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Entidades.Animal", b =>
                {
                    b.HasOne("Entities.Entidades.Cliente", "Cliente")
                        .WithMany("Animais")
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Entities.Entidades.Cliente", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "UsuarioSistemaClinica")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioSistemaClinica");
                });

            modelBuilder.Entity("Entities.Entidades.Compra", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.Consulta", b =>
                {
                    b.HasOne("Entities.Entidades.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("ID_Animal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "UsuarioSistemaClinica")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("ID_Veterinario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("UsuarioSistemaClinica");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Entities.Entidades.Consulta_Exame", b =>
                {
                    b.HasOne("Entities.Entidades.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ID_Consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Exame", "Exame")
                        .WithMany()
                        .HasForeignKey("ID_Exame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Exame");
                });

            modelBuilder.Entity("Entities.Entidades.Estoque", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.Exame", b =>
                {
                    b.HasOne("Entities.Entidades.Cliente", "Cliente")
                        .WithMany("Exames")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Entities.Entidades.Familia", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.Fornecedor", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.ItemProdutoCompra", b =>
                {
                    b.HasOne("Entities.Entidades.Compra", null)
                        .WithMany("Produtos")
                        .HasForeignKey("CompraIdCompra");

                    b.HasOne("Entities.Entidades.Compra", "Compra")
                        .WithMany("ItemProdutoCompras")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Produto", "Produto")
                        .WithMany("ItemProdutoCompras")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Entities.Entidades.ItemProdutoEstoque", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("IdEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.ItemProdutoVenda", b =>
                {
                    b.HasOne("Entities.Entidades.Produto", "Produto")
                        .WithMany("ItemProdutoVendas")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Venda", "Venda")
                        .WithMany("ItemProdutoVendas")
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Entities.Entidades.Mercadoria", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.NotaFiscal", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.VendaServicoPagamento", "VendaServicoPagamento")
                        .WithMany()
                        .HasForeignKey("IdVendaServicoPagamento");

                    b.Navigation("Usuario");

                    b.Navigation("VendaServicoPagamento");
                });

            modelBuilder.Entity("Entities.Entidades.PedidoServicos", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany("PedidoServicos")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.PedidoServicosRelacao", b =>
                {
                    b.HasOne("Entities.Entidades.PedidoServicos", "PedidoServicos")
                        .WithMany("PedidoServicosRelacoes")
                        .HasForeignKey("IdPedidoServicos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoServicos");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Entities.Entidades.Produto", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.UnspscCode", "UnspscCode")
                        .WithMany()
                        .HasForeignKey("IdUnspsc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnspscCode");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.Secretaria", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "UsuarioSistemaClinica")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioSistemaClinica");
                });

            modelBuilder.Entity("Entities.Entidades.Segmento", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.Servico", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.UnspscCode", "UnspscCode")
                        .WithMany()
                        .HasForeignKey("IdUnspsc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnspscCode");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.UnspscCode", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infra.Configuracao.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Mercadoria", "Mercadoria")
                        .WithMany()
                        .HasForeignKey("IdMercadoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.Segmento", "Segmento")
                        .WithMany()
                        .HasForeignKey("IdSegmento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Familia");

                    b.Navigation("Mercadoria");

                    b.Navigation("Segmento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.Venda", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entidades.VendaServicoPagamento", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.PedidoServicos", "PedidoServico")
                        .WithMany()
                        .HasForeignKey("IdPedidoServicos");

                    b.HasOne("Entities.Entidades.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PedidoServico");

                    b.Navigation("Usuario");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Entities.Entidades.Veterinario", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "UsuarioSistemaClinica")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioSistemaClinica");
                });

            modelBuilder.Entity("Infra.Configuracao.Classe", b =>
                {
                    b.HasOne("Entities.Entidades.UsuarioSistemaClinica", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Entidades.Cliente", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Exames");
                });

            modelBuilder.Entity("Entities.Entidades.Compra", b =>
                {
                    b.Navigation("ItemProdutoCompras");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Entities.Entidades.PedidoServicos", b =>
                {
                    b.Navigation("PedidoServicosRelacoes");
                });

            modelBuilder.Entity("Entities.Entidades.Produto", b =>
                {
                    b.Navigation("ItemProdutoCompras");

                    b.Navigation("ItemProdutoVendas");
                });

            modelBuilder.Entity("Entities.Entidades.UsuarioSistemaClinica", b =>
                {
                    b.Navigation("PedidoServicos");
                });

            modelBuilder.Entity("Entities.Entidades.Venda", b =>
                {
                    b.Navigation("ItemProdutoVendas");
                });
#pragma warning restore 612, 618
        }
    }
}
